FROM ubuntu:bionic

ENV USER=testuser

COPY setup.py /

RUN apt-get update -yqq
RUN apt-get install -yqq lsb-release sudo ca-certificates gnupg

RUN useradd -s /bin/bash -G sudo testuser
RUN mkdir /home/testuser
RUN chown -R testuser:testuser /home/testuser

RUN echo "testuser ALL=(ALL) NOPASSWD:ALL" | tee -a /etc/sudoers

USER testuser
WORKDIR /home/testuser

RUN cat /setup.py | python3 - --docker --nvm --jetbrains --davfs --keepassxc --overwrite-zsh --micro
